#! /bin/bash

sxhkd -c ~/.config/bspwm/themes/bspwm_pac/sxhkd/sxhkdrc &
picom --config ~/.config/bspwm/themes/bspwm_pac/picom/picom.conf &
xsetroot -cursor_name left_ptr &
nm-applet &
~/.fehbg &
~/.config/bspwm/themes/bspwm_pac/scripts/launch_polybar.sh &
dunst -conf ~/.config/bspwm/themes/bspwm_pac/dunst/dunstrc &
otd-daemon &

firefox &
kitty &
spotify-launcher &
steam &

bspc rule -a firefox desktop='^1'
bspc rule -a kitty desktop='^2'
bspc rule -a spotify-launcher desktop='^3'
bspc rule -a Spotify desktop='^3'
bspc rule -a steam desktop='^3'
bspc rule -a ripdrag state=floating

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 3
bspc config window_gap 10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d6d1ff"
bspc config presel_feedback_color "#2e3440"

bspc config split_ratio 0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
