chmod +x ~/.config/bspwm/bspwmrc
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/cava.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/volume.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/powermenu.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/wallchange.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/wallselect.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/notify-send.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/toggle_picom.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/launch_polybar.sh
chmod +x ~/.config/bspwm/themes/bspwm_pac/scripts/screenshot.sh
