#! /bin/bash

xrandr --output DP-1 --mode 1920x1080
sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &
picom --config ~/.config/bspwm/picom/picom.conf &
feh --bg-fill --randomize ~/.config/bspwm/wallpapers &
nm-applet &
~/.config/bspwm/scripts/launch_polybar.sh &
dunst -conf ~/.config/bspwm/dunst/dunstrc &
otd-daemon &

firefox &
alacritty &

bspc rule -a firefox desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a spotify-launcher desktop='^3'
bspc rule -a Spotify desktop='^3'
bspc rule -a steam desktop='^3'
bspc rule -a ripdrag state=floating

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 3
bspc config window_gap 10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#d6d1ff"
bspc config focused_border_color "#d6d1ff"
bspc config presel_feedback_color "#2e3440"

bspc config split_ratio 0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
